---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
- name: concourse-sample-app

outputs:
- name: package-output

run:
  path: concourse-sample-app/ci/tasks/package.sh
